#!/usr/bin/env node
/**
 * Generates THIRD_PARTY_LICENSES.txt and sbom.json for the PRODUCTION
 * dependencies only — the packages that actually ship in the npm tarball.
 * Supply-chain honesty: a reader can see every third-party package we bundle,
 * its version, its license, and the license text, plus a CycloneDX SBOM a
 * scanner can read. Run: npm run sbom  (also run by the release gate).
 *
 * Dev dependencies are intentionally excluded — they are not distributed.
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();

function prodTree() {
  const raw = execSync("npm ls --omit=dev --all --json", { cwd: ROOT, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
  return JSON.parse(raw);
}

/** Flatten the npm ls tree into a unique name@version map. */
function collect(node, out = new Map()) {
  const deps = node.dependencies ?? {};
  for (const [name, info] of Object.entries(deps)) {
    if (!info || info.version === undefined) continue; // unmet optional dep: not shipped
    const key = `${name}@${info.version}`;
    if (!out.has(key)) out.set(key, { name, version: info.version });
    collect(info, out);
  }
  return out;
}

function pkgDir(name) {
  const direct = join(ROOT, "node_modules", name);
  return existsSync(direct) ? direct : null;
}

function licenseOf(dir) {
  try {
    const pj = JSON.parse(readFileSync(join(dir, "package.json"), "utf-8"));
    const lic = pj.license ?? (Array.isArray(pj.licenses) ? pj.licenses.map((l) => l.type).join(" OR ") : "UNKNOWN");
    return typeof lic === "string" ? lic : "UNKNOWN";
  } catch {
    return "UNKNOWN";
  }
}

function licenseText(dir) {
  try {
    const f = readdirSync(dir).find((n) => /^(licen[sc]e|copying)(\.|$)/i.test(n));
    if (f) return readFileSync(join(dir, f), "utf-8").trim();
  } catch {
    /* fall through */
  }
  return null;
}

const tree = prodTree();
const pkgs = [...collect(tree).values()].sort((a, b) => a.name.localeCompare(b.name));

// ---- THIRD_PARTY_LICENSES.txt ----
const licLines = [
  "THIRD-PARTY SOFTWARE LICENSES",
  "",
  `RuleReceipt bundles the following third-party packages in its published npm`,
  `package (production dependencies only; dev dependencies are not distributed).`,
  `Generated by scripts/generate-sbom.mjs on ${new Date().toISOString().slice(0, 10)}.`,
  "",
  "=".repeat(78),
  "",
];
for (const { name, version } of pkgs) {
  const dir = pkgDir(name);
  const license = dir ? licenseOf(dir) : "UNKNOWN";
  licLines.push(`${name}@${version}  —  ${license}`);
  const text = dir ? licenseText(dir) : null;
  if (text) {
    licLines.push("");
    licLines.push(text);
  }
  licLines.push("");
  licLines.push("-".repeat(78));
  licLines.push("");
}
writeFileSync(join(ROOT, "THIRD_PARTY_LICENSES.txt"), licLines.join("\n"));

// ---- sbom.json (CycloneDX 1.5, minimal) ----
const self = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf-8"));
const sbom = {
  bomFormat: "CycloneDX",
  specVersion: "1.5",
  version: 1,
  metadata: {
    timestamp: new Date().toISOString(),
    component: { type: "application", name: self.name, version: self.version, purl: `pkg:npm/${self.name}@${self.version}` },
    tools: [{ name: "generate-sbom.mjs", vendor: "RuleReceipt" }],
  },
  components: pkgs.map(({ name, version }) => {
    const dir = pkgDir(name);
    return {
      type: "library",
      name,
      version,
      purl: `pkg:npm/${name}@${version}`,
      licenses: dir ? [{ license: { id: licenseOf(dir) } }] : [],
    };
  }),
};
writeFileSync(join(ROOT, "sbom.json"), JSON.stringify(sbom, null, 2) + "\n");

console.log(`Wrote THIRD_PARTY_LICENSES.txt and sbom.json for ${pkgs.length} production packages.`);
for (const { name, version } of pkgs) console.log(`  ${name}@${version} — ${pkgDir(name) ? licenseOf(pkgDir(name)) : "UNKNOWN"}`);
